import Head from "next/head";
import Header from "../components/Header";
import Photo from "../components/Photo";
import About from "../components/About";
import Hero1 from "../assets/images/desktop-image-hero-1.jpg";
import Hero2 from "../assets/images/desktop-image-hero-2.jpg";
import Hero3 from "../assets/images/desktop-image-hero-3.jpg";
import AboutImg from "../assets/images/image-about-light.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Room homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Photo src={Hero1} className={"w-full h-[400px]"} alt="room photo" />
      <About />
      <Photo src={Hero2} className={"w-full h-[200px]"} alt="room photo" />
      <Photo src={Hero3} className={"w-full h-[250px]"} alt="room photo" />
      <Photo src={AboutImg} className={"w-full h-[250px]"} alt="room photo" />
    </>
  );
}
