import Head from "next/head";
import Header from "../components/Header";
import About from "../components/About";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Room homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <About />
    </>
  );
}
